### ISSUE TITLE
Need ability to zim non articlespace pages

### ISSUE THREAD

**Issue by sodabottle** [tecoholic/zimbalaka#17]
Need the tool to pull non mainspace pages as well like from the project space. Example: zim the featured pics archive from tamil wikipedia. So the article list looks like the following

விக்கிப்பீடியா:இன்றைய சிறப்புப் படம்/மே 17, 2015
விக்கிப்பீடியா:இன்றைய சிறப்புப் படம்/சூன் 3, 2015
விக்கிப்பீடியா:இன்றைய சிறப்புப் படம்/2015

**Comment by sodabottle** [comment]
URLs:
https://ta.wikipedia.org/wiki/%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%80%E0%AE%9F%E0%AE%BF%E0%AE%AF%E0%AE%BE:%E0%AE%87%E0%AE%A9%E0%AF%8D%E0%AE%B1%E0%AF%88%E0%AE%AF_%E0%AE%9A%E0%AE%BF%E0%AE%B1%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%AA%E0%AF%8D_%E0%AE%AA%E0%AE%9F%E0%AE%AE%E0%AF%8D/%E0%AE%9A%E0%AF%86%E0%AE%AA%E0%AF%8D%E0%AE%9F%E0%AE%AE%E0%AF%8D%E0%AE%AA%E0%AE%B0%E0%AF%8D_30,_2015

https://ta.wikipedia.org/wiki/%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%80%E0%AE%9F%E0%AE%BF%E0%AE%AF%E0%AE%BE:%E0%AE%87%E0%AE%A9%E0%AF%8D%E0%AE%B1%E0%AF%88%E0%AE%AF_%E0%AE%9A%E0%AE%BF%E0%AE%B1%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%AA%E0%AF%8D_%E0%AE%AA%E0%AE%9F%E0%AE%AE%E0%AF%8D/%E0%AE%86%E0%AE%95%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AF%81_9,_2015

https://ta.wikipedia.org/wiki/%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%80%E0%AE%9F%E0%AE%BF%E0%AE%AF%E0%AE%BE:%E0%AE%87%E0%AE%A9%E0%AF%8D%E0%AE%B1%E0%AF%88%E0%AE%AF_%E0%AE%9A%E0%AE%BF%E0%AE%B1%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81%E0%AE%AA%E0%AF%8D_%E0%AE%AA%E0%AE%9F%E0%AE%AE%E0%AF%8D/%E0%AE%9A%E0%AF%82%E0%AE%B2%E0%AF%88_26,_2015

https://ta.wikipedia.org/wiki/%E0%AE%AA%E0%AE%AF%E0%AE%A9%E0%AE%B0%E0%AF%8D:Sodabottle/%E0%AE%83%E0%AE%AA%E0%AE%AF%E0%AE%B0%E0%AF%8D%E0%AE%83%E0%AE%AA%E0%AF%8D%E0%AE%B3%E0%AF%88

**Comment by sodabottle** [comment]
More:
https://commons.wikimedia.org/wiki/File:Mozambique_-_traditional_sailboat.jpg
https://commons.wikimedia.org/wiki/File:17_Years_of_Sekar_Jepun_2014-11-01_05.jpg
https://commons.wikimedia.org/wiki/File:Chaplin_The_Kid_edit.jpg

**Comment by tecoholic** [comment]
Thanks for the input. Discovered that code base is untestable after tinkering around. Might need a complete rewrite.

**Comment by kelson42** [comment]
This will be easy with mwoffliner (see #16), zimbalaka just need to provide the UI to provide a way to configure this.

**Comment by tecoholic** [comment]
@kelson42 I think, it is hightime I dropped the Python module and switched to mwoffliner. Working on it shortly.

**Comment by kelson42** [comment]
Great, will try to setup stats for zimbalaka.openzim.org to measure the audience.

**Comment by tecoholic** [comment]
Issue fixed with code. Now live at http://www.srik.me/zimbalaka/.

The transition to mwoffliner still remains.
